root = "."
testdata_dir = "testdata"
bin_dir = "bin"

[env]
  PORT = "8080"
  MARK1_CONFIG_PATH="etc/main.yaml"

[build]
  args_bin = []
  bin = "./bin/server"
  cmd = "dlv debug --headless --listen=:8080 --log --api-version=2 --output=debug/__debug_bin cmd/server/main.go"
  after = "rm -f debug/__debug_bin*" 
  delay = 1000
  exclude_dir = ["assets", "bin", "vendor", "testdata"]
  exclude_file = []
  exclude_regex = ["_test.go"]
  exclude_unchanged = false
  follow_symlink = false
  full_bin = ""
  include_dir = []
  include_ext = ["go", "tpl", "tmpl", "html"]
  include_file = []
  kill_delay = "0s"
  poll = false
  poll_interval = 0
  post_cmd = []
  pre_cmd = []
  rerun = false
  rerun_delay = 500
  send_interrupt = false
  stop_on_error = false

[color]
  app = ""
  build = "yellow"
  main = "magenta"
  runner = "green"
  watcher = "cyan"

[log]
  main_only = false
  time = false

[misc]
  clean_on_exit = false

[screen]
  clear_on_rebuild = false
  keep_scroll = true
