ARG TOKEN=""
FROM ryoarima/ubuntu-arm:latest
ENV GH_TOKEN=$TOKEN

WORKDIR /root

COPY ./.. /root/mark1

RUN echo "Start" && \
    pwd && ls -la && \
    cd /root/mark && \
    make build-bin && \
    make build-deb && \
    make push-deb

CMD [ "echo", "This is mark1" ]
