name: Release

on:
  push:
    branches: [ "main" ]

jobs:
  deb-build:
    runs-on: ubuntu-latest
    container: ryoarima/ubuntu-base:latest
    steps:
      - uses: actions/checkout@v4
      - name: Build Bin,Deb & Publish
        run: |
          make build-bin
          make build-deb
          make push-deb TOKEN=${{ secrets.MARK1_TOKEN }}

  rpm-build:
    runs-on: ubuntu-latest
    container: ryoarima/rocky-base:latest
    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: |
          make build-bin
          make build-rpm