name: Release

on:
  push:
    branches: [ "main" ]

jobs:
  deb-build:
    runs-on: ubuntu-latest
    container: ryoarima/ubuntu-base:latest
    steps:
      - uses: actions/checkout@v4

      # Test phase after building
      - name: Test
        run: go test ./... -v
      
        # Normal build phase before testing
      - name: Build
        run: make build-deb

  rpm-build:
    runs-on: ubuntu-latest
    container: ryoarima/rocky-base:latest
    steps:
      - uses: actions/checkout@v4

      # Test phase after building
      - name: Test
        run: go test ./... -v
      
        # Normal build phase before testing
      - name: Build
        run: make build-rpm