name: Release

on:
  push:
    branches: [ "main" ]

jobs:
  base-deb-build:
    runs-on: ubuntu-latest
    container: ryoarima/ubuntu-base:latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up a Git safe directory
        run: git config --global --add safe.directory "${GITHUB_WORKSPACE}"
      - name: Build Bin,Deb & Publish
        env:
          GH_TOKEN: ${{ secrets.MARK1_TOKEN }}
        run: |
          make build-bin
          make build-deb
          make push-deb 

  base-rpm-build:
    runs-on: ubuntu-latest
    container: ryoarima/rocky-base:latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up a Git safe directory
        run: git config --global --add safe.directory "${GITHUB_WORKSPACE}"
      - name: Build Bin,Rpm & Publish
        env:
          GH_TOKEN: ${{ secrets.MARK1_TOKEN }}
        run: |
          make build-bin
          make build-rpm
          make push-rpm
  
  arm-deb-build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: arm64
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Check out the code
        uses: actions/checkout@v4
      - name: Build ARM PKG on container
        env:
          GH_TOKEN: ${{ secrets.MARK1_TOKEN }}
        run: |
          docker run --platform linux/arm64 --rm -v ${GITHUB_WORKSPACE}:/root/mark1 -e GH_TOKEN=${GH_TOKEN} ryoarima/ubuntu-arm:latest bash -c "cd /root/mark1 && make build-bin && make build-deb && make push-deb"