name: Release

on:
  push:
    branches: [ "main" ]

jobs:
  deb-build:
    runs-on: ubuntu-latest
    container: ryoarima/ubuntu-base:latest
    steps:
      - uses: actions/checkout@v4

      # Normal build phase before testing
      - name: Build
        run: go build -v cmd/client/anonymous/main.go

      # Test phase after building
      - name: Test
        run: go test ./... -v

      # Release build phase
      - name: Release Build
        run: go build -ldflags="-s -w" -o release/main cmd/client/anonymous/main.go

  rpm-build:
    runs-on: ubuntu-latest
    container: ryoarima/rocky-base:latest
    steps:
      - uses: actions/checkout@v4

      # Normal build phase before testing
      - name: Build
        run: go build -v cmd/client/anonymous/main.go

      # Test phase after building
      - name: Test
        run: go test ./... -v

      # Release build phase
      - name: Release Build
        run: go build -ldflags="-s -w" -o release/main cmd/client/anonymous/main.go