name: UPDATE README

on:
    workflow_dispatch:
      inputs:
        name:
          description: ""
          required: true
          default: "update-readme"

jobs:
  ubuntu-base-mark1:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Log in to DockerHub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build and push Docker image
        run: |
          docker build -f tool/docker/base-ubuntu.dockerfile -t ${{ secrets.DOCKERHUB_USERNAME }}/ubuntu-base-mark1:latest .
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/ubuntu-base-mark1:latest
      - name: Log out from DockerHub
        run: docker logout

  rocky-base-mark1:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Log in to DockerHub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build and push Docker image
        run: |
          docker build -f tool/docker/base-rocky.dockerfile -t ${{ secrets.DOCKERHUB_USERNAME }}/rocky-base-mark1:latest .
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/rocky-base-mark1:latest
      - name: Log out from DockerHub
        run: docker logout
  
  rocky-arm-mark1:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: arm64
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Check out the code
        uses: actions/checkout@v4
      - name: Build ARM PKG on container
        run: |
          echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin
          docker build --platform linux/arm64 -f tool/docker/arm-rocky.dockerfile -t ${{ secrets.DOCKERHUB_USERNAME }}/rocky-arm-mark1:latest .
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/rocky-arm-mark1:latest
  
  ubuntu-arm-mark1:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: arm64
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Check out the code
        uses: actions/checkout@v4
      - name: Build ARM PKG on container
        run: |
          echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin
          docker build --platform linux/arm64 -f tool/docker/arm-ubuntu.dockerfile -t ${{ secrets.DOCKERHUB_USERNAME }}/ubuntu-arm-mark1:latest .
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/ubuntu-arm-mark1:latest